import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import ModalProvider from "./components/providers/modal-provider";
import { SocketProvider } from "./components/providers/socket-provider";
import { QueryProvider } from "./components/providers/query-provider";
import Navbar from "./components/Navabar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark bg-black scroll-smooth overflow-x-hidden" >
      <body className={inter.className}>
       <Navbar/>
        <ModalProvider />
        <SocketProvider>
          <QueryProvider>
            {children}
          </QueryProvider>
        </SocketProvider>
        <Toaster />
      </body>
    </html>
  );
}
