import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navabar";
import { Toaster } from "@/components/ui/toaster"
import ModalProvider from "./components/providers/modal-provider";
// import { PrimeReactProvider } from 'primereact/api';
// import 'primeicons/primeicons.css';
// import 'primeflex/primeflex.css';
// import 'primereact/resources/primereact.css';
// import 'primereact/resources/themes/lara-light-indigo/theme.css'; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark bg-black scroll-smooth" >
      <body className={inter.className}>
      {/* <PrimeReactProvider> */}
        <Navbar/>
        <ModalProvider/>
        {children}
        <Toaster />
        {/* </PrimeReactProvider> */}
        </body>
    </html>
  );
}
